export const GET_SADMIN_USER = "GET_SADMIN_USER"
export const GET_SADMIN_USER_SUCCESSFUL = "GET_SADMIN_USER_SUCCESSFUL"
export const GET_SADMIN_USER_FAIL = "GET_SADMIN_USER_FAIL"

export const ADD_NEW_SADMIN_USER = "ADD_NEW_SADMIN_USER"
export const ADD_NEW_SADMIN_USER_SUCCESSFUL = "ADD_NEW_SADMIN_USER_SUCCESSFUL"
export const ADD_NEW_SADMIN_USER_FAIL = "ADD_NEW_SADMIN_USER_FAIL"

export const UPDATE_SADMIN_USER = "UPDATE_SADMIN_USER"
export const UPDATE_SADMIN_USER_SUCCESSFUL = "UPDATE_SADMIN_USER_SUCCESSFUL"
export const UPDATE_SADMIN_USER_FAIL = "UPDATE_SADMIN_USER_FAIL"

export const DELETE_SADMIN_USER = "DELETE_SADMIN_USER"
export const DELETE_SADMIN_USER_SUCCESSFUL = "DELETE_SADMIN_USER_SUCCESSFUL"
export const DELETE_SADMIN_USER_FAIL = "DELETE_SADMIN_USER_FAIL"

export const ACTIVEINACTIVE_SADMIN_USER = "ACTIVEINACTIVE_SADMIN_USER"
export const ACTIVEINACTIVE_SADMIN_USER_SUCCESSFUL = "ACTIVEINACTIVE_SADMIN_USER_SUCCESSFUL"
export const ACTIVEINACTIVE_SADMIN_USER_FAIL = "ACTIVEINACTIVE_SADMIN_USER_FAIL"