export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_SUCCESSFUL = "LOGIN_USER_SUCCESSFUL"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"

export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_SUCCESSFUL = "LOGOUT_USER_SUCCESSFUL"