export const GET_ADMIN_USER = "GET_ADMIN_USER"
export const GET_ADMIN_USER_SUCCESSFUL = "GET_ADMIN_USER_SUCCESSFUL"
export const GET_ADMIN_USER_FAIL = "GET_ADMIN_USER_FAIL"

export const ADD_NEW_ADMIN_USER = "ADD_NEW_ADMIN_USER"
export const ADD_NEW_ADMIN_USER_SUCCESSFUL = "ADD_NEW_ADMIN_USER_SUCCESSFUL"
export const ADD_NEW_ADMIN_USER_FAIL = "ADD_NEW_ADMIN_USER_FAIL"

export const UPDATE_ADMIN_USER = "UPDATE_ADMIN_USER"
export const UPDATE_ADMIN_USER_SUCCESSFUL = "UPDATE_ADMIN_USER_SUCCESSFUL"
export const UPDATE_ADMIN_USER_FAIL = "UPDATE_ADMIN_USER_FAIL"

export const DELETE_ADMIN_USER = "DELETE_ADMIN_USER"
export const DELETE_ADMIN_USER_SUCCESSFUL = "DELETE_ADMIN_USER_SUCCESSFUL"
export const DELETE_ADMIN_USER_FAIL = "DELETE_ADMIN_USER_FAIL"

export const ACTIVEINACTIVE_ADMIN_USER = "ACTIVEINACTIVE_ADMIN_USER"
export const ACTIVEINACTIVE_ADMIN_USER_SUCCESSFUL = "ACTIVEINACTIVE_ADMIN_USER_SUCCESSFUL"
export const ACTIVEINACTIVE_ADMIN_USER_FAIL = "ACTIVEINACTIVE_ADMIN_USER_FAIL"