export const GET_USER = "GET_USER"
export const GET_USER_SUCCESSFUL = "GET_USER_SUCCESSFUL"
export const GET_USER_FAIL = "GET_USER_FAIL"

export const ADD_NEW_USER = "ADD_NEW_USER"
export const ADD_NEW_USER_SUCCESSFUL = "ADD_NEW_USER_SUCCESSFUL"
export const ADD_NEW_USER_FAIL = "ADD_NEW_USER_FAIL"

export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_USER_SUCCESSFUL = "UPDATE_USER_SUCCESSFUL"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"

export const DELETE_USER = "DELETE_USER"
export const DELETE_USER_SUCCESSFUL = "DELETE_USER_SUCCESSFUL"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const ACTIVEINACTIVE_USER = "ACTIVEINACTIVE_USER"
export const ACTIVEINACTIVE_USER_SUCCESSFUL = "ACTIVEINACTIVE_USER_SUCCESSFUL"
export const ACTIVEINACTIVE_USER_FAIL = "ACTIVEINACTIVE_USER_FAIL"